/**
 * Generates BLS test vectors for the Stylus verifier AND proves the on-chain
 * hash-to-curve pipeline against the live EIP-2537 precompiles on Robinhood Chain:
 *
 *   hash_to_field (off-chain, RFC 9380) -> MAP_FP2_TO_G2 x2 -> G2ADD -> == noble hashToCurve
 *   PAIRING_CHECK(-G1, sig, pk, H(m)) == 1   (valid)   and   == 0 (tampered)
 *
 * Uses a fixed, publicly known TEST seed — never a real key.
 * Usage: pnpm bls:vectors [rpcUrl]
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { bytesToHex, hexToBytes, keccak256, toHex, type Hex } from 'viem';
import { expand_message_xmd } from '@noble/curves/abstract/hash-to-curve';
import { sha256 } from '@noble/hashes/sha2';
import {
  INTENT_DST,
  encodeG1,
  encodeG2,
  hashToFieldFp2,
  hashToG2,
  keypairFromSeed64,
  negG1Generator,
  publicKeyPoint,
  publicKeyUncompressed,
  signDigest,
  verifyDigest,
} from '../src/amadeus/bls.js';

const RPC = process.argv[2] ?? 'https://rpc.testnet.chain.robinhood.com';
const PRECOMPILE = {
  g2Add: '0x000000000000000000000000000000000000000d',
  pairing: '0x000000000000000000000000000000000000000f',
  mapFp2ToG2: '0x0000000000000000000000000000000000000011',
} as const;

async function ethCall(to: string, data: Uint8Array): Promise<Hex> {
  const res = await fetch(RPC, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'eth_call', params: [{ to, data: bytesToHex(data) }, 'latest'] }),
  });
  const json = (await res.json()) as { result?: Hex; error?: { message: string } };
  if (!json.result) throw new Error(`eth_call ${to} failed: ${json.error?.message ?? 'no result'}`);
  return json.result;
}

function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(`ASSERTION FAILED: ${message}`);
  console.log(`ok  ${message}`);
}

const concat = (...p: Uint8Array[]) => hexToBytes(`0x${p.map((x) => bytesToHex(x).slice(2)).join('')}`);

async function main(): Promise<void> {
  const seed = hexToBytes(keccak256(toHex('agentic-yield-vaults/test-seed-a')) + keccak256(toHex('agentic-yield-vaults/test-seed-b')).slice(2) as Hex);
  const { publicKey, secretKey } = keypairFromSeed64(seed);
  const digest = keccak256(toHex('agentic-yield-vaults/test-intent-digest'));
  const message = hexToBytes(digest);

  const signature = signDigest(digest, secretKey);
  assert(verifyDigest(digest, signature.compressed, publicKey), 'noble verifies the intent signature');

  const uniform = expand_message_xmd(message, INTENT_DST, 256, sha256);
  const [u0, u1] = hashToFieldFp2(message);
  const expectedH = encodeG2(hashToG2(message));

  const q0 = await ethCall(PRECOMPILE.mapFp2ToG2, u0!);
  const q1 = await ethCall(PRECOMPILE.mapFp2ToG2, u1!);
  const h = await ethCall(PRECOMPILE.g2Add, concat(hexToBytes(q0), hexToBytes(q1)));
  assert(h === bytesToHex(expectedH), 'MAP_FP2_TO_G2 x2 + G2ADD on-chain == noble hashToCurve');

  const pk = encodeG1(publicKeyPoint(publicKey));
  const sig = hexToBytes(signature.uncompressed);
  const valid = await ethCall(PRECOMPILE.pairing, concat(negG1Generator(), sig, pk, expectedH));
  assert(BigInt(valid) === 1n, 'PAIRING_CHECK accepts the valid signature on-chain');

  const otherH = encodeG2(hashToG2(hexToBytes(keccak256(toHex('tampered')))));
  const invalid = await ethCall(PRECOMPILE.pairing, concat(negG1Generator(), sig, pk, otherH));
  assert(BigInt(invalid) === 0n, 'PAIRING_CHECK rejects a signature over another message');

  const vectors = {
    dst: INTENT_DST,
    digest,
    publicKeyCompressed: bytesToHex(publicKey),
    publicKeyUncompressed: publicKeyUncompressed(publicKey),
    signatureCompressed: signature.compressed,
    signatureUncompressed: signature.uncompressed,
    uniformBytes: bytesToHex(uniform),
    u0: bytesToHex(u0!),
    u1: bytesToHex(u1!),
    q0,
    q1,
    hashToG2: bytesToHex(expectedH),
    negG1: bytesToHex(negG1Generator()),
  };

  const rust = [
    '// @generated by agent/scripts/bls-vectors.ts — do not edit by hand.',
    '// Test-only key derived from a public seed; validated against live EIP-2537 precompiles.',
    ...Object.entries(vectors).map(
      ([k, v]) => `pub const ${k.replace(/[A-Z]/g, (c) => `_${c}`).toUpperCase()}: &str = "${v}";`,
    ),
    '',
  ].join('\n');
  const rustPath = resolve(import.meta.dirname, '../../contracts/stylus/bls-verifier/src/test_vectors.rs');
  writeFileSync(rustPath, rust);
  const jsonPath = resolve(import.meta.dirname, '../test/fixtures/bls-vectors.json');
  writeFileSync(jsonPath, `${JSON.stringify(vectors, null, 2)}\n`);
  console.log(`wrote ${rustPath}\nwrote ${jsonPath}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
