/**
 * Writes the EIP-712 parity fixture consumed by the Rust vault tests, using viem's
 * reference `hashTypedData`. Usage: pnpm tsx scripts/eip712-vectors.ts
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { keccak256, toHex } from 'viem';
import { intentDigest, REGIME, type RebalanceIntent } from '../src/intent/eip712.js';

const CHAIN_ID = 46630;

const intent: RebalanceIntent = {
  vault: '0x00000000000000000000000000000000000000aa',
  nonce: 7n,
  deadline: 1_790_000_000n,
  regime: REGIME.VOLATILE,
  morphoBps: 6_000,
  uniswapBps: 3_000,
  volBps: 4_250,
  inputsHash: keccak256(toHex('inputs')),
  modelVersion: keccak256(toHex('ayv-policy-v1')),
};

const digest = intentDigest(CHAIN_ID, intent);
const rust = [
  '// @generated by agent/scripts/eip712-vectors.ts (viem hashTypedData) — do not edit by hand.',
  `pub const CHAIN_ID: u64 = ${CHAIN_ID};`,
  `pub const VAULT: &str = "${intent.vault}";`,
  `pub const NONCE: u64 = ${intent.nonce};`,
  `pub const DEADLINE: u64 = ${intent.deadline};`,
  `pub const REGIME: u8 = ${intent.regime};`,
  `pub const MORPHO_BPS: u16 = ${intent.morphoBps};`,
  `pub const UNISWAP_BPS: u16 = ${intent.uniswapBps};`,
  `pub const VOL_BPS: u16 = ${intent.volBps};`,
  `pub const INPUTS_HASH: &str = "${intent.inputsHash}";`,
  `pub const MODEL_VERSION: &str = "${intent.modelVersion}";`,
  `pub const DIGEST: &str = "${digest}";`,
  '',
].join('\n');

const path = resolve(import.meta.dirname, '../../contracts/stylus/vault/src/eip712_vectors.rs');
writeFileSync(path, rust);
writeFileSync(
  resolve(import.meta.dirname, '../test/fixtures/eip712-vector.json'),
  `${JSON.stringify({ chainId: CHAIN_ID, intent: { ...intent, nonce: '7', deadline: '1790000000' }, digest }, null, 2)}\n`,
);
console.log(`digest ${digest}\nwrote ${path}`);
