[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
evm_version = "prague"
optimizer = true
optimizer_runs = 800
via_ir = false
bytecode_hash = "none"
fs_permissions = [{ access = "read-write", path = "../../deployments" }, { access = "read", path = "./" }, { access = "read", path = "../../agent/test/fixtures" }]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
robinhood_testnet = "${RPC_URL}"
