// @generated by agent/scripts/eip712-vectors.ts (viem hashTypedData) — do not edit by hand.
pub const CHAIN_ID: u64 = 46630;
pub const VAULT: &str = "0x00000000000000000000000000000000000000aa";
pub const NONCE: u64 = 7;
pub const DEADLINE: u64 = 1790000000;
pub const REGIME: u8 = 1;
pub const MORPHO_BPS: u16 = 6000;
pub const UNISWAP_BPS: u16 = 3000;
pub const VOL_BPS: u16 = 4250;
pub const INPUTS_HASH: &str = "0xd41d6b189e130a016c166c65c226d7fa1a53be2afafef394b142a39dc9c054cd";
pub const MODEL_VERSION: &str = "0x7f304cf4b47f3d73de8809d9c0f1341c1e77925a6f4529baff9d00c488dd9466";
pub const DIGEST: &str = "0xd8306408ae0c4fe397308536e70fa1143bf34f6f92586b3d0dab9f908a980132";
